[tool.poetry]
name = "git-poetry"
version = "0.1.0"
description = ""
authors = ["Valery Medvedev <walery.medvedev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
